"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { ChevronLeft, FileText, Loader2, Share2 } from "lucide-react";
import dynamic from "next/dynamic";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useRef } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { orpc } from "@/lib/orpc-client";
import { FeedbackSection } from "./_components/feedback-section";
import { InterviewSummary } from "./_components/interview-summary";
import { InterviewTimeline } from "./_components/interview-timeline";
import { OverallScoreCard } from "./_components/overall-score-card";
import { PDFDownloadButton } from "./_components/pdf-download-button";
import { TranscriptSection } from "./_components/transcript-section";

const ReportRadarChart = dynamic(
  () =>
    import("./_components/report-radar-chart").then(
      (mod) => mod.ReportRadarChart,
    ),
  {
    ssr: false,
    loading: () => (
      <div className="h-[400px] animate-pulse bg-muted rounded-lg" />
    ),
  },
);

export default function InterviewReportPage() {
  const params = useParams<{ interviewId: string }>();
  const router = useRouter();
  const queryClient = useQueryClient();
  const transcriptRef = useRef<HTMLDivElement>(null);

  // Fetch real interview data from the backend
  // The report is generated by the 'end' mutation in session.ts using Gemini
  const { data, isLoading, error } = useQuery(
    orpc.interview.getById.queryOptions({
      input: { id: params.interviewId },
    }),
  );

  const { mutateAsync: retryEndSession, isPending: isRetryingReport } =
    useMutation(orpc.interview.end.mutationOptions());

  const handleRetryReport = useCallback(async () => {
    if (!data?.interview) return;
    try {
      await retryEndSession({
        interviewId: params.interviewId,
        durationSec: data.interview.durationSec,
      });
      await queryClient.invalidateQueries();
      toast.success("Report generated successfully");
    } catch {
      toast.error("Report generation failed. Please try again.");
    }
  }, [data, params.interviewId, retryEndSession, queryClient]);

  const handleTimelineNodeClick = useCallback((messageId: string) => {
    // Find the Q&A pair element and scroll to it
    const element = document.querySelector(`[data-message-id="${messageId}"]`);
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, []);

  if (isLoading) {
    return (
      <div className="flex flex-col gap-6 p-6 max-w-7xl mx-auto w-full">
        <div className="flex items-center gap-4">
          <Skeleton className="h-10 w-10 rounded-md" />
          <div className="space-y-2">
            <Skeleton className="h-6 w-48" />
            <Skeleton className="h-4 w-32" />
          </div>
        </div>
        {/* Summary skeleton */}
        <Skeleton className="h-[200px] rounded-xl" />
        {/* Score cards skeleton */}
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <Skeleton className="h-[350px] rounded-xl" />
          <Skeleton className="h-[350px] rounded-xl md:col-span-2" />
        </div>
        {/* Timeline skeleton */}
        <Skeleton className="h-[100px] rounded-xl" />
        {/* Transcript skeleton */}
        <Skeleton className="h-[400px] rounded-xl" />
        {/* Feedback skeleton */}
        <Skeleton className="h-[300px] rounded-xl" />
      </div>
    );
  }

  if (error || !data?.interview) {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center p-6 bg-background">
        <Card className="w-full max-w-md border-border shadow-sm">
          <CardContent className="flex flex-col items-center gap-6 p-8 text-center">
            <div className="p-4 rounded-full bg-destructive/10 ring-1 ring-destructive/20 mb-2">
              <FileText className="h-8 w-8 text-destructive" />
            </div>
            <div className="space-y-2">
              <h2 className="font-heading text-2xl font-bold tracking-tight text-foreground">
                Report Unavailable
              </h2>
              <p className="text-muted-foreground text-sm leading-relaxed">
                {error
                  ? "We couldn't load the report at this time. Our systems might be experiencing a temporary hiccup."
                  : "The requested interview could not be found. It may have been relocated or deleted."}
              </p>
            </div>
            <Button
              onClick={() => router.push("/dashboard")}
              className="w-full mt-2"
            >
              Return to Dashboard
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const { interview } = data;
  const report = interview.report;

  // Handle case where report hasn't been generated yet
  if (!report) {
    return (
      <div className="flex min-h-[80vh] flex-col items-center justify-center p-6 bg-background">
        <Card className="w-full max-w-md border-border shadow-sm">
          <CardContent className="flex flex-col items-center gap-6 p-8 text-center">
            <div className="relative mb-2">
              <div className="absolute inset-0 rounded-full blur-xl bg-primary/20 animate-pulse" />
              <div className="relative p-4 rounded-full bg-background border border-border shadow-sm">
                <FileText className="h-8 w-8 text-primary animate-pulse" />
              </div>
            </div>
            <div className="space-y-2">
              <h2 className="font-heading text-2xl font-bold tracking-tight text-foreground">
                Processing Report
              </h2>
              <p className="text-muted-foreground text-sm leading-relaxed">
                Our AI is currently analyzing your interview data to generate
                comprehensive insights. This usually takes just a moment.
              </p>
            </div>
            <div className="flex w-full gap-3 mt-4">
              <Button
                variant="outline"
                onClick={() => router.back()}
                className="flex-1"
              >
                Go Back
              </Button>
              <Button
                onClick={handleRetryReport}
                disabled={isRetryingReport}
                className="flex-1"
              >
                {isRetryingReport ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  "Generate Report"
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Transform real backend data for the chart
  const radarData = [
    { category: "Communication", score: report.categoryScores.communication },
    {
      category: "Problem Solving",
      score: report.categoryScores.problemSolving,
    },
    { category: "Technical", score: report.categoryScores.technicalKnowledge },
    { category: "Code Quality", score: report.categoryScores.codeQuality },
    { category: "Time Mgmt", score: report.categoryScores.timeManagement },
  ];

  return (
    <div className="flex flex-col gap-8 p-6 max-w-7xl mx-auto w-full animate-in fade-in duration-700">
      {/* Header Section */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b border-border/40 pb-6">
        <div className="flex items-start gap-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => router.push("/dashboard")}
            title="Back to Dashboard"
            className="mt-1 hover:bg-muted/50"
          >
            <ChevronLeft className="h-5 w-5" />
          </Button>
          <div className="space-y-1">
            <h1 className="text-3xl font-bold tracking-tight bg-linear-to-r from-foreground to-foreground/70 bg-clip-text text-transparent">
              Interview Report
            </h1>
            <p className="text-muted-foreground flex items-center gap-2 text-sm">
              <span className="font-medium text-foreground">
                {interview.jobTitle}
              </span>
              <span className="text-muted-foreground/50">•</span>
              <span>
                {format(new Date(interview.startedAt), "MMMM d, yyyy")}
              </span>
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" className="shadow-sm">
            <Share2 className="mr-2 h-4 w-4" />
            Share
          </Button>
          <PDFDownloadButton interview={interview} report={report} />
        </div>
      </div>

      {/* AI Summary Section */}
      <InterviewSummary
        summary={report.summary}
        jobTitle={interview.jobTitle}
        type={interview.type}
        experienceLevel={interview.experienceLevel}
        techStack={
          typeof interview.techStack === "string"
            ? (interview.techStack as string).split(",").map((t) => t.trim())
            : interview.techStack || []
        }
        durationSec={interview.durationSec}
        startedAt={interview.startedAt}
      />

      {/* Score Grid */}
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {/* Overall Score with Animation */}
        <div className="lg:col-span-1 h-[380px]">
          <OverallScoreCard score={report.overallScore} />
        </div>

        {/* Radar Chart Analysis */}
        <div className="lg:col-span-2 h-[380px]">
          <ReportRadarChart data={radarData} />
        </div>
      </div>

      {/* Timeline Navigation */}
      {interview.messages && interview.messages.length > 0 && (
        <InterviewTimeline
          messages={interview.messages}
          onNodeClick={handleTimelineNodeClick}
        />
      )}

      {/* Interactive Transcript */}
      {interview.messages && interview.messages.length > 0 && (
        <div ref={transcriptRef}>
          <TranscriptSection messages={interview.messages} />
        </div>
      )}

      {/* Detailed Feedback Sections */}
      <div className="w-full">
        <FeedbackSection
          strengths={report.strengths ?? []}
          weaknesses={report.weaknesses ?? []}
          suggestions={report.suggestions ?? []}
        />
      </div>
    </div>
  );
}
